const cityList = [
	{ id: 1, label: "강남구", value: "Gangnam-gu" },
	{ id: 2, label: "강동구", value: "Gangdong-gu" },
	{ id: 3, label: "강북구", value: "Gangbuk-gu" },
	{ id: 4, label: "강서구", value: "Gangseo-gu" },
	{ id: 5, label: "관악구", value: "Gwanak-gu" },
	{ id: 6, label: "광진구", value: "Gwangjin-gu" },
	{ id: 7, label: "구로구", value: "Guro-gu" },
	{ id: 8, label: "금천구", value: "Geumcheon-gu" },
	{ id: 9, label: "도봉구", value: "Dobong-gu" },
	{ id: 10, label: "동대문구", value: "Dongdaemun-gu" },
	{ id: 11, label: "동작구", value: "Dongjak-gu" },
	{ id: 12, label: "마포구", value: "Mapo-gu" },
	{ id: 13, label: "서대문구", value: "Seodaemun-gu" },
	{ id: 14, label: "서초구", value: "Seocho-gu" },
	{ id: 15, label: "성동구", value: "Seongdong-gu" },
	{ id: 16, label: "성북구", value: "Seongbuk-gu" },
	{ id: 17, label: "송파구", value: "Songpa-gu" },
	{ id: 18, label: "양천구", value: "Yangcheon-gu" },
	{ id: 19, label: "영등포구", value: "Yeongdeungpo-gu" },
	{ id: 20, label: "용산구", value: "Yongsan-gu" },
	{ id: 21, label: "은평구", value: "Eunpyeong-gu" },
	{ id: 22, label: "종로구", value: "Jongno-gu" },
	{ id: 23, label: "중구", value: "Jung-gu" },
];

export default cityList;
