const cities = [
	{ label: "강남구", value: "Gangnam-gu" },
	{ label: "강동구", value: "Gangdong-gu" },
	{ label: "강북구", value: "Gangbuk-gu" },
	{ label: "강서구", value: "Gangseo-gu" },
	{ label: "관악구", value: "Gwanak-gu" },
	{ label: "광진구", value: "Gwangjin-gu" },
	{ label: "구로구", value: "Guro-gu" },
	{ label: "금천구", value: "Geumcheon-gu" },
	{ label: "노원구", value: "Nowon-gu" },
	{ label: "도봉구", value: "Dobong-gu" },
	{ label: "동대문구", value: "Dongdaemun-gu" },
	{ label: "동작구", value: "Dongjak-gu" },
	{ label: "마포구", value: "Mapo-gu" },
	{ label: "서대문구", value: "Seodaemun-gu" },
	{ label: "서초구", value: "Seocho-gu" },
	{ label: "성동구", value: "Seongdong-gu" },
	{ label: "성북구", value: "Seongbuk-gu" },
	{ label: "송파구", value: "Songpa-gu" },
	{ label: "양천구", value: "Yangcheon-gu" },
	{ label: "영등포구", value: "Yeongdeungpo-gu" },
	{ label: "용산구", value: "Yongsan-gu" },
	{ label: "은평구", value: "Eunpyeong-gu" },
	{ label: "종로구", value: "Jongno-gu" },
	{ label: "중구", value: "Jung-gu" },
	{ label: "중랑구", value: "Jungnang-gu" },
];

export default cities;
